"""My comment

Revision ID: 37e1a4f3e317
Revises: 46fb5eb2a1df
Create Date: 2024-11-30 01:33:47.419724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37e1a4f3e317'
down_revision: Union[str, None] = '46fb5eb2a1df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'promocode',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('products', 'size')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('size', sa.INTEGER(), nullable=False))
    op.alter_column('orders', 'promocode',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
