"""Your migration message

Revision ID: 4a171b3129f5
Revises: c9f86592b1c3
Create Date: 2024-11-29 02:46:15.633800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '4a171b3129f5'
down_revision: Union[str, None] = 'c9f86592b1c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:


    inspector = inspect(op.get_bind())
    if 'orders' not in inspector.get_table_names():
    # ### commands auto generated by Alembic - please adjust! ###
        op.create_table('orders',
        sa.Column('promocode', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###

# /Users/vladdremenko/Micro_Shop/env/alembic/versions/4a171b3129f5_your_migration_message.py