"""My comment

Revision ID: 798fc123f1de
Revises: 46fb5eb2a1df
Create Date: 2024-11-30 03:14:16.909384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '798fc123f1de'
down_revision: Union[str, None] = '46fb5eb2a1df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'promocode',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'promocode',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
