"""Initial migration

Revision ID: 9b9208c20b87
Revises: 
Create Date: 2024-11-30 05:09:34.864041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b9208c20b87'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_product_association', sa.Column('unit_price', sa.Integer(), server_default='0', nullable=False))
    op.drop_constraint('idx_unique_order_products', 'order_product_association', type_='unique')
    op.create_unique_constraint('idx_unique_order_product', 'order_product_association', ['order_id', 'product_id'])
    op.alter_column('orders', 'promocode',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'promocode',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('idx_unique_order_product', 'order_product_association', type_='unique')
    op.create_unique_constraint('idx_unique_order_products', 'order_product_association', ['order_id', 'product_id'])
    op.drop_column('order_product_association', 'unit_price')
    # ### end Alembic commands ###
    pass
