"""add count column to assosiation tabel

Revision ID: aba9e2ecaa31
Revises: 46fb5eb2a1df
Create Date: 2024-11-30 03:21:51.803098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aba9e2ecaa31'
down_revision: Union[str, None] = '46fb5eb2a1df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_product_association', sa.Column('count', sa.Integer(), server_default='1', nullable=False))
    op.alter_column('orders', 'promocode',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'promocode',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('order_product_association', 'count')
    # ### end Alembic commands ###
